### ISSUE TITLE
Do you know why people dont like to make rat public?

### ISSUE THREAD

**Issue by opabravo** [Sp00p64/DiscordRAT#4]
Think of my question, and you will understand why people wont create pull request on this repo.
Because they make better ones, and never let the public to know, so that's why the rat isn't "DISCOVERED".
Please, dont make the idea public

**Comment by Sp00p64** [comment]
I do not care about pull requests, if people want to do some then fine, if they don't it's also fine because I am fully aware that they are better RATS , mine never was meant to be a super powerful tool,it's just an idea that I wanted to post because i've spent  some times on it.I'll make it public if I damn want to.
